# Generated by Django 3.1.5 on 2021-02-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidnightBlue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
